version: '2'
volumes:
    dashboard-data:
    sensor-data:
services:
  sensor:
    build: ./sensor
    privileged: true
    restart: never
    network_mode: host
  dashboard:
    image: balenablocks/dashboard:raspberrypi3
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  influxdb:
    image: influxdb@sha256:b099bdd1f4306689fd11c02f83b3de7fc11eccd8debf5f345e9be11d0a7cd7dc
    container_name: influxdb
    restart: always
    volumes:
      -   sensor-data:/data'
  connector:
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    privileged: true # necessary to change container hostname
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always