version: '2'
volumes:
  log:
services:
  sensor:
    build: ./sensor
    privileged: true
    restart: never
    network_mode: host
    volumes:
      - 'log:/mnt/log'
    labels:
      io.balena.features.supervisor-api: '1'
